Renew date parser
AinoMegumi/CalendarServer pull request #11
Opened 2022-03-21 16:54 UTC by AinoMegumi

2022-03-27 15:26 UTC, yumetodo commented on spec/AnnoToJP.js
> +    const beginInfo = Borders[i];
```suggestion
    const beginInfo = Borders.find(b => b.alphabet === era || b.jcalendar === era || b.jcalendar.substring(0, 1) === era);
    if (beginInfo == null) return null;
```

2022-03-27 15:33 UTC, yumetodo commented on spec/AnnoToJP.js
> +        return { begin: beginJson }
```suggestion
    if (found_i  === Borders.length - 1) {
        // 関数切り出し
```

2022-03-27 16:07 UTC, AinoMegumi commented on spec/AnnoToJP.js
> +        return { begin: beginJson }
applied ```92b2d30```

2022-03-27 16:08 UTC, AinoMegumi commented on spec/AnnoToJP.js
> +    const beginInfo = Borders[i];
applied 92b2d30

2022-04-03 14:15 UTC, AinoMegumi commented
基幹部のdate parserは置換完了を確認

2022-04-04 09:53 UTC, yumetodo requested changes
- 7f1665b, e051372 変更の意図が書かれていません

2022-04-23 08:05 UTC, AinoMegumi commented
7f1665b および e051372 についてコミットメッセージを変更した

2022-04-23 11:10 UTC, yumetodo approved these changes

2022-05-05 15:39 UTC, merged